# docker-compose.yml
version: "3.9"
services:
  webapp:
    image: hsienchao/oncogenomics
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./oncogenomics:/var/www/html/clinomics
      - /mnt/nci_ccr_gb_oncogenomics_sg:/mnt/nci_ccr_gb_oncogenomics_sg
    hostname: oncogenomics-dev.cancer.gov
    domainname: cancer.gov
    env_file:
      - ./.env    
  
