# docker-compose.yml
version: "3.9"
services:
  webapp:
    image: hsienchao/oncogenomics:latest
    build:
      context: .
      args:
        INCUBATOR_VER: ${now}
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      #- ./clinomics:/var/www/html/clinomics
      - /mnt/nci_ccr_gb_oncogenomics_sg:/var/www/html/clinomics/site_data
    env_file:
      - ./.env
  
